### ISSUE TITLE
Great update for push notification, but there are errors on the demo

### ISSUE THREAD

**Issue by zadcall** [voximplant/flutter_demos#3] opened 2020-04-02 02:48 UTC
Hi @VladimirBrejcha ,

Thanks for the update, but the way you handle the push notification can't be work as it  should be, at the demo too I faced the following problems:

1- When I start the call it give me the status "connecting ..." and it last for only 20 seconds, and that's not enough to handle from other device to click on the notification, so we hope if you can login the other user when he receive the push notification either he clicked or didn't click on the notification, so that the "ringing.." status can be change the timeout to be like a 60 sec and that's a good time so that the other user can answer the call.

2- when the call failed, without the other user answer ( as example after 20 sec, or if the other user canceled for any reason) and then the receiver tried to click on the notification, the application still opens on incoming call screen and when he click to answer the page still give him "connecting .." without anything else and cannot be closed, see this video https://jmp.sh/zn8qyfV

3- I tried to check the method pushNotificationReceived so I can add there anything to loggin the user or add a print value or anything that cannot be printed, so I don't know from where I can change the notification that has been sent to the device, I need to change the "Incoming call" message on the notifcation as example, from where exactly can I get to that ?!

**Comment by VladimirBrejcha** [comment] 2020-04-07 13:31
Hi @zadcall ,

1. Technically Voximplant SDK works like that: After push is sent to you, you'll have 20 seconds to login and if it happened you'll have another 40 seconds to answer. Otherwise caller will receive call failed. But in current implementation of VideoCall Flutter Demo it is not handled as intended. We are working on it, expect it to be fixed in the next demo update.
2. This is bugged just in demo, expect it to be fixed in the next demo update.
3. I didn't quite get you, but to change text in notification (in our demo) you can try to play with the flutterLocalNotificationsPlugin.show method. In the demo it is used here https://github.com/voximplant/flutter_demos/blob/master/video_call/lib/services/notification_service.dart#L40

**Closed** 2020-09-23 10:51 UTC
